### ISSUE TITLE
`Ols4Client` search always yields `ValidationError`

### ISSUE THREAD

**Issue by maarten-devries** [ahida-development/ols-py#6]
Any search using `Ols4Client`, e.g. this line from the tests `resp = ols4_client.search(query="patella", params={"ontology": "mondo", "rows": 10})`

returns the following error for me
```
ValidationError: 1 validation error for SearchResponse
docs
  field required (type=value_error.missing)
```

I don't have so much Pydantic experience, so I don't see an obvious solution here, but just thought I'd point it out.

**Comment by marius-mather** [comment]
@maarten-devries unfortunately OLS4 has been changing its response structure during development (generally bringing it back in sync with OLS3, but not always), and the approach I have taken with trying to specify the exact structure with pydantic models is not very robust to this. I've just updated the package to `0.5.0` now and search should be working, but may break again if more changes occur in the API's responses.

Hopefully when OLS4 is released I will have a working package that aligns with the final API schema, until then I can't promise this will work consistently!

**Comment by maarten-devries** [comment]
Got it, totally understand it's under rapid development. Thanks for the great package by the way!
